%YAML 1.2
---
OccupancyGrid:
  width: 320
  height: 320
  resolution_m: 0.05 
  obstacles:
    - [2.0, 14.0, 1.5, 1.0]
    - [5.0, 9.0, 4.0, 3.0]
    - [6.0, 4.0, 4.0, 1.0]
    - [9.0, 12.0, 1.0, 5.0]
    - [11.0, 10.0, 1.5, 1.0]
    - [12.0, 6.0, 1.5, 1.0]
    - [14.0, 14.0, 1.5, 1.0]

PlannerType: AStar # BFS | Dijkstra | AStar
Start: [1.0, 7.0, 0.0]
End: [11.0, 14.0, 0.0]